blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, change_is_active

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('article/<slug>', BlogDetailView.as_view(), name='article'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<slug>', BlogUpdateView.as_view(), name='update'),
    path('delete/<slug>', BlogDeleteView.as_view(), name='delete'),
    path('change_is_active/<slug>', change_is_active, name='change_is_active'), 
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import os, sys
sys.path.append(os.getcwd())

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(unique=True, max_length=170, verbose_name='ЧПУРЛ')
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(verbose_name='превью', null=True, blank=True)
    create_at = models.DateTimeField(default=timezone.now(), verbose_name='дата создания')
    is_active = models.BooleanField(default=True, verbose_name='признак публикации')
    views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self) -> str:
        return f'{self.title}'
    
    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/views.py
from typing import Any
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Blog
from pytils.translit import slugify

from blog.utils import send_mail_to_admin



class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog
    slug_field = 'slug' 

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        if self.object.views % 5 == 0:
            send_mail_to_admin(self.object)
        return self.object
    

class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    permission_required = 'blog.add_blog'
    fields =('title', 'body', 'preview', 'is_active', )
    success_url = reverse_lazy('blog:list') 

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            if Blog.objects.filter(slug=new_article.slug).exists():
                new_article.slug = f'{new_article.slug}-{new_article.pk}'
            new_article.save()
        return super().form_valid(form)


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    permission_required = 'blog.change_blog'
    fields =('title', 'body', 'preview', 'is_active', )

    def get_success_url(self) -> str:
        return reverse('blog:article', args=[self.kwargs.get('slug')])
    

class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = 'blog.delete_blog'
    success_url = reverse_lazy('blog:list')


def change_is_active(request, slug):
    article = get_object_or_404(Blog, slug=slug)
    article.is_active = not article.is_active
    article.save()

    return redirect(reverse('blog:article', args=[slug]))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset enable>
        <legend>Удалить статью: "{{ object }}" ?</legend>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url "blog:list" %}" class="btn btn-light">Отмена</a>
    </fieldset>
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class=container>
    <div class="row">
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a class="btn mb-3 btn-warning" href="{% url 'blog:update' object.slug %}">Изменить</button>
            <a class="btn mb-3 btn-danger" href="{% url 'blog:delete' object.slug %}">Удалить</button>
            {% if object.is_active %}
                <a class='btn mb-3 btn-outline-dark' href="{% url 'blog:change_is_active' object.slug %}">Деактивировать</a>
            {% else %}
                <a class='btn mb-3 btn-outline-dark' href="{% url 'blog:change_is_active' object.slug %}">Опубликовать</a>
            {% endif %}
        </div> 
        <div class="card mb-3 col-12 align-content-center">
            <center>
                <img src="/media/{{ object.preview }}" class="card-img-top" alt="Нет картинки", style="width: 300px; height: 300px;">
            </center>
        </div>
    </div>
</div>
<div class="row">
    <div class="card mb-3 col-12">
        <h3 class="card-title mt-3 mb-3 text-center">{{ object.title }} </h3>
        <p class="card-text mb-5 text-center">{{ object.body }}</p>
        <strong class="d-inline-block mb-2 text-primary">
            {% if object.is_active %}
                Опубликован
            {% else %}
                Не опубликован
            {% endif %}
        </strong>
        <p class="card-text">Дата создания: {{ object.create_at|date:"d.m.Y H:i:s" }}</p>
        <p class="card-text">Просмотров: {{ object.views }}</p>
    </div> 
</div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset enable>
        <legend>Добавить статью</legend>
        <form method="post" class="my-class">
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </fieldset>
</form>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% if perms.blog.add_blog %}
            <a class="p-2 btn btn-outline-primary" href="{% url "blog:create" %}">Создать</a>
        {% endif %}
    </div>
</div>
<div class="row mb-2">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'blog/includes/inc_blog_cart.html' %}
        {% endfor %}
    </div>
</div>

{% endblock content %}