blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, change_is_active

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('article/<slug>', BlogDetailView.as_view(), name='article'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<slug>', BlogUpdateView.as_view(), name='update'),
    path('delete/<slug>', BlogDeleteView.as_view(), name='delete'),
    path('change_is_active/<slug>', change_is_active, name='change_is_active'), 
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import os, sys
sys.path.append(os.getcwd())

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import os, sys
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from users.views import MyPasswordResetView, MyPasswordResetCompleteView, MyPasswordResetConfirmView, MyPasswordResetDoneView, RegisterView, ProfileView, EmailConfirmationView
sys.path.append(os.getcwd())


from django.urls import path, reverse_lazy
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name = "users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('register/confirm/', EmailConfirmationView.as_view(), name='email_confirmation'),

    path('profile/', ProfileView.as_view(), name='profile'),

    path('password_reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', MyPasswordResetDoneView.as_view(), name='password_reset_done'), 
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    
    username = None
    email = models.EmailField(verbose_name='email', unique=True)
    avatar = models.ImageField(upload_to='users/',verbose_name='аватар', blank=True, null=True)
    phone = models.IntegerField(verbose_name='телефон', blank=True, null=True)
    country = models.CharField(max_length=150, verbose_name='страна', blank=True, null=True)
    confirmation_code = models.IntegerField(verbose_name='код верификации', blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth import forms
from django.forms import ValidationError, CharField, Form

from users.models import User


class MyUserCreationForm(forms.UserCreationForm):
    
    class Meta:
        fields = ('email','password1', 'password2',)
        model = User



class EmailConfirmationForm(Form):
    confirmation_code = CharField(max_length=6)

    def clean_confirmation_code(self):
        confirmation_code = self.cleaned_data.get('confirmation_code')
        if not User.objects.filter(confirmation_code=confirmation_code).exists():
            raise ValidationError('Неверный код подтверждения.')
        return confirmation_code

users/views.py
import random
from django.conf import settings
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetView
from django.core.mail import send_mail
from django.forms import ValidationError
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, FormView, UpdateView
from users.forms import EmailConfirmationForm, MyUserCreationForm

from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = MyUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:email_confirmation')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.object = form.save()
        code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        self.object.confirmation_code = code
        self.object.save()
        
        send_mail(
            subject='Подтверждение почты MolokoShop',
            message=f'Ваш проверочный код: {code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )

        return super().form_valid(form)

class EmailConfirmationView(FormView):
    form_class = EmailConfirmationForm
    template_name = 'users/email_confirmation.html'
    success_url = reverse_lazy('catalog:products')


    def form_valid(self, form):
        confirmation_code = form.cleaned_data['confirmation_code']
        user = User.objects.get(confirmation_code=confirmation_code)
        user.confirmation_code = None
        user.save()
        return super().form_valid(form)


class MyPasswordResetView(PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    

class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name="users/password_reset_done.html"

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name='users/password_reset_confirm.html'
    success_url = reverse_lazy("users:password_reset_complete")

class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name='users/password_reset_complete.html'



class ProfileView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', 'avatar', 'phone', 'country')
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        
        return self.request.user 

users/templates/users/email_confirmation.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class='justify-content-center d-flex flex-row'>
    <form method="POST" enctype="multipart/form-data">
        <fieldset enable>
            <legend>Введите код подтверждения</legend>
            <form method="post" class="my-class">
                {% csrf_token %}
                {{ form|crispy }}
            </form>
            <button type="submit" class="btn btn-primary">Войти</button>
        </fieldset>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-10">
            <form method="POST" enctype="multipart/form-data">

                <fieldset enable>
                    <legend>Войти</legend>
                    <form method="post" class="my-class">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a href="{% url "users:password_reset" %}" class="btn btn-danger">Забыл пароль</a>

                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-10">
<form method="post" enctype="multipart/form-data">
    <h1 class="h3 mb-3 fw-normal form-signin w-100">Сброс пароля</h1>
    <p class="text text-black">Введите ваш адрес электронной почты для сброса пароля.</p>
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-primary w-100 py-2" type="submit">Отправить письмо для сброса пароля</button>
</form>
</div>
</div>

</div> 
{% comment %} <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
        </div>
    </form>
</div> {% endcomment %}
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'users:login' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Сброс пароля</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Сброс пароля</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Ссылка выслана на почту. Если настройки не меняли то письмо сохранено в корне проекта в папке send_emails
    </div>
{% endblock content %}

users/templates/users/password_reset_email.html
{% extends "catalog/base.html" %}
{% load i18n %}{% autoescape off %}

{% block content %}
    <p>{% blocktranslate %}Вы получили это письмо т.к запросили новый пароль {{ site_name }}.{% endblocktranslate %}</p>
    
    <p>{% translate "Пожалуйте следуйте по ссылке и введите новый пароль:" %}</p>
    <p><a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">Сброс пароля</a></p>

    <p>{% translate 'Ваш email для входа на сайт:' %} {{ user.get_username }}</p>

    <p>{% translate "Thanks for using our site!" %}</p>
    <p>{% blocktranslate %}The {{ site_name }} {{ site_name }} {% endblocktranslate %}</p>
{% endblock %}
{% endautoescape %}

users/templates/users/profile.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="POST" enctype="multipart/form-data">
                
                <fieldset enable>
                    <legend>Войти</legend>
                    <form method="post" class="my-class">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a href="{% url "users:password_reset" %}" class="btn btn-danger">Выслать новый пароль на почту</a>
                </fieldset>
            </form>
</div>
</div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class='justify-content-center d-flex flex-row'>
<form method="POST" enctype="multipart/form-data">
    
    <fieldset enable>
        <legend>Войти</legend>
        <form method="post" class="my-class">
            {% csrf_token %}
            {{ form|crispy }}
        </form>
        <button type="submit" class="btn btn-primary">Войти</button>
    </fieldset>
</form>
</div>
{% endblock %}