blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, change_is_active

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('article/<slug>', BlogDetailView.as_view(), name='article'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<slug>', BlogUpdateView.as_view(), name='update'),
    path('delete/<slug>', BlogDeleteView.as_view(), name='delete'),
    path('change_is_active/<slug>', change_is_active, name='change_is_active'), 
]

catalog/urls.py
import os, sys

from django.views.decorators.cache import cache_page, never_cache
sys.path.append(os.getcwd())

from django.urls import path
from catalog.views import ContactCreateView, ProductDetialView, ProductListView, ProductCreateView, ProductUpdateView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    # path('', products, name='products'),
    # path('contacts/', contact, name='contacts'),
    # path('product/', product),
    # path('add_product/', add_product, name='add_product'),
    
    path('', ProductListView.as_view(), name='products'),
    path('contacts/', never_cache(ContactCreateView.as_view()), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetialView.as_view()), name='product'),
    path('add_product/', never_cache(ProductCreateView.as_view()), name='add_product'),
    path('update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='update'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import os, sys
sys.path.append(os.getcwd())

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import os, sys
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from users.views import MyPasswordResetView, MyPasswordResetCompleteView, MyPasswordResetConfirmView, MyPasswordResetDoneView, RegisterView, ProfileView, EmailConfirmationView
sys.path.append(os.getcwd())


from django.urls import path, reverse_lazy
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name = "users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('register/confirm/', EmailConfirmationView.as_view(), name='email_confirmation'),

    path('profile/', ProfileView.as_view(), name='profile'),

    path('password_reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', MyPasswordResetDoneView.as_view(), name='password_reset_done'), 
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

catalog/models.py
from django.db import models
from django.utils import timezone

from users.models import User 

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    
    name = models.CharField(max_length=100, verbose_name='Наименование', **NULLABLE)
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'
    
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)

class Product(models.Model): 
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', **NULLABLE)
    price = models.FloatField(verbose_name='Цена за покупку')
    created_at = models.DateTimeField(default=timezone.now(), verbose_name='Дата создания')
    last_change_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name='опубликован')

    def __str__(self):
        return f'{self.name}({self.category}): {self.description}\
            \nЦена:{self.price}\
            \nДата создания: {self.created_at}\
            \nДата последнего изменения: {self.last_change_date}\n'
    
    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('id',)



class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя', null=True, blank=True)
    phone = models.BigIntegerField(verbose_name='Телефон', null=True, blank=True)
    message = models.TextField(verbose_name='Сообщение', null=True, blank=True)

    def __str__(self):
        return f'{self.name}, {self.phone}\nСообщение: {self.message}'
    
    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('id',)

class Version(models.Model):
    CHOICES = (
        (1, "1 - Старт"),
        (2, "2- Базовый"),
        (3, "3 - Начал нормально работать"),
        (4, "4 - Я устал работать"),
        (5, "5 - Все, больше не сделаю"),
)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='id продукта')
    version = models.IntegerField(choices=CHOICES, verbose_name='версия')
    name = models.CharField(max_length=150, verbose_name='название')
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self) -> str:
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

        # чтобы нельзя было создавать несколько активных версий для одного продукта
        constraints = [
            models.UniqueConstraint(
                fields=['product'],
                condition=models.Q(is_active=True),
                name='only_one_active_version_for_product',
            ),
        ]

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from django.conf import settings


class ProductStaffForm(forms.ModelForm):
    """ Формирование формы продуктов """

    class Meta:
        """ Описание формы продуктов """

        model = Product
        fields = ("description", "category", "is_published",)




class ProductForm(forms.ModelForm):
    """ Формирование формы продуктов """

    class Meta:
        """ Описание формы продуктов """

        model = Product
        fields = ("name", "description", "preview", "category", "price", "is_published",)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = 'Some help text for field'

    def clean_name(self):
        """ Проверяет стоп слова в названии """

        name = self.cleaned_data.get('name')

        if self._field_contains_forbidden_words(name):
                raise forms.ValidationError('Название содержит запрещенные слова')

        return name
    
    def clean_description(self):
        """ Проверяет стоп слова в описании """

        description = self.cleaned_data.get('description')

        if self._field_contains_forbidden_words(description):
                raise forms.ValidationError('Название содержит запрещенные слова')
        
        return description

    @staticmethod
    def _field_contains_forbidden_words(field_value: str) -> bool:
        field_value = field_value.lower()
        return any(field_value in forbidden_word for forbidden_word in settings.STOP_WORDS_LIST)



class VersionForm(forms.ModelForm):
    
    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
import os, sys
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.forms import ValidationError
from django.http import Http404, HttpResponse

from catalog.services import get_all_products_from_cache_or_db
sys.path.append(os.getcwd())

from catalog.models import Contact, Product, Version

## CBV-метод
from django.urls import reverse, reverse_lazy
from catalog.forms import ProductForm, ProductStaffForm, VersionForm
from django.views.generic import DetailView, CreateView, ListView, UpdateView
from django.forms.models import BaseModelForm, inlineformset_factory



class ContactCreateView(CreateView):
	model = Contact
	fields = ('name', 'phone', 'message', )
	success_url = reverse_lazy('catalog:products')


class ProductListView(ListView):
    model = Product
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                context_data['object_list'] = get_all_products_from_cache_or_db()
            else:
                context_data['object_list'] = Product.objects.filter(owner=self.request.user)
        for product in context_data.get('object_list', []):
            active_version = product.version_set.filter(is_active=True).last()
            if active_version:
                product.active_version_number = active_version.version
                product.active_version_name = active_version.name
            else:
                product.active_version_number = "Нет версии"
                product.active_version_name = None
        return context_data
	


class ProductDetialView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'
    
    def get_object(self, *args, **kwargs):
        self.object = super().get_object(*args, **kwargs)
        if self.object.owner == self.request.user or self.request.user.is_staff:
            return self.object
        raise Http404
        

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(pk=self.kwargs.get('pk'))
        return queryset
    

class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:products')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    template_name = 'catalog/product_form_with_formset.html'

    def get_form_class(self):
        form_class = super().get_form_class()
        if self.request.user.is_staff and self.object.owner != self.request.user:
            form_class = ProductStaffForm
        return form_class

    def get_object(self, *args, **kwargs):
        self.object = super().get_object(*args, **kwargs)
        if self.object.owner == self.request.user or self.request.user.is_staff:
            return self.object
        raise Http404
    
    def get_success_url(self, *args, **kwargs):
        return reverse('catalog:update', args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if not self.request.user.is_staff:
            SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
            else:
                context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
		# self.object = form.save() для создания

        if len([product.get('is_active') for product in formset.cleaned_data if product.get('is_active')]) > 1:
            raise ValidationError('Возможна лишь одна активная версия. Пожалуйста, активируйте только 1 версию.')

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)




## FBV-метод

# from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.shortcuts import render
# from django.urls import reverse

# def products(request):
# 	all_products = Product.objects.all() 
# 	paginator = Paginator(all_products, 3)  
# 	page = request.GET.get('page')

# 	try:
# 		products = paginator.page(page)
# 	except PageNotAnInteger:
# 		products = paginator.page(1)
# 	except EmptyPage:
# 		products = paginator.page(paginator.num_pages)
# 	context = {'object_list': products,} 
# 	return render(request, 'catalog/products.html', context)


# def contact(request):
# 	if request.method == 'POST':
# 		name = request.POST.get('name')
# 		phone = request.POST.get('phone')
# 		message = request.POST.get('message')
# 		Contact.objects.create(name=name, phone=phone, message=message)
# 	return render(request, 'catalog/contact.html')


# def product(request):
# 	first_object = Product.objects.all().first()
# 	context = {'object': first_object}

# 	return render(request, 'catalog/product.html', context)


# def add_product(request):
# 	categories = Category.objects.all()
# 	context = {'object_list': categories}
# 	if request.method == 'POST':
# 		name = request.POST.get('name')
# 		description = request.POST.get('description')
# 		preview = request.FILES['preview']
# 		category_name = request.POST.get('category')
# 		category = Category.objects.get(name=category_name)
# 		price = request.POST.get('price')

# 		Product.objects.create(name=name, description=description, preview=preview, category=category, price=price)
# 	return render(request, 'catalog/add_product.html', context)

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset enable>
        <legend>Добавить товар</legend>

        <div class="mb-3">
            <input type="name" name="name" id="disabledTextInput" class="form-control" placeholder="Наименование">
        </div>

        <div class="mb-3">
            <input type="text" name="description" id="disabledTextInput" class="form-control" placeholder="Описание">
        </div>

        <div class="mb-3">
            <select class="form-select" name="category" aria-label="Default select example" >
                <option selected>Выбирите категорию</option>
                {% for object in object_list %}
                    <option value="{{ object }}">{{ object }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <input type="file" name="preview" class="form-control" aria-label="file example" required>
            <div class="invalid-feedback">Нет файла</div>
        </div>

        <div class="mb-3">
            <input type="text" name="price" id="disabledTextInput" class="form-control" placeholder="Цена в рублях">
        </div>

        <button type="submit" class="btn btn-primary">Создать</button>
    </fieldset>
</form>








{% endblock %}

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static '/css/bootstrap.min.css'%}" rel="stylesheet">
    <style>
        .pagination {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }
    
        .step-links {
            display: inline-block;
            margin: 0 15px;
        }
    
        .step-links a {
            text-decoration: none;
            color: #333;
            font-weight: bold;
            margin: 0 5px;
        }
    
        .current-page {
            font-weight: bold;
            margin: 0 5px;
        }
    </style>
    
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url "catalog:products" %}">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="{% url "blog:list" %}">Блог</a>
            <a class="p-2 btn btn-outline-primary" href="{% url "catalog:contacts" %}">Контакты</a>
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url "catalog:add_product" %}">Создать товар</a>
                <a class="p-2 btn btn-outline-primary" href="{% url "users:profile" %}">Профиль</a>
                <a class="p-2 btn btn-outline-primary" href="{% url "users:logout" %}">Выйти</a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url "users:login" %}">Войти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url "users:register" %}">Регистрация</a>
            {% endif %}

        </nav>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>

</body>

</html>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                    required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                    placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                    placeholder="Контактный телефон" required></textarea>
                            </div>
                            <div class="mb-3">
                                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/contact_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-3 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-9 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <form method="post" class="my-class">
                                {{ form|crispy }}
                            </form>
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Применить
                                {% else %}
                                    Отправить
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_product_cart.html' %}
        {% endfor %}
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ products.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current-page">
            Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">следующая</a>
            <a href="?page={{ object_list.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="card mb-3 col-3">
        <img src="{% mediapath object.preview %}" class="card-img-top" alt="Нет картинки", style="width: 300px; height: 300px;">
    </div>
    <div class="card mb-3 col-9">
        <h3 class="card-title mt-3 mb-3 text-center">{{ object.name }} ({{ object.category }}) </h3>
    
        <p class="card-text mb-5 text-center">{{ object.description }}</p>
        <h5 class="card-text">Цена: {{ object.price }} руб.</h5>
        <h5 class="card-text">Дата создания: {{ object.created_at|date:"d.m.Y H:i:s" }}</h5>
    </div> 
</div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class="row">
    <div class="card mb-3 col-3">
        <img src="{% mediapath object.preview %}" class="card-img-top" alt="Нет картинки", style="width: 300px; height: 300px;">
    </div>
    <div class="card mb-3 col-9">
        <h3 class="card-title mt-3 mb-3 text-center">{{ object.name }} ({{ object.category }}) </h3>
    
        <p class="card-text mb-5 text-center">{{ object.description }}</p>
        <h5 class="card-text">Цена: {{ object.price }} руб.</h5>
        <h5 class="card-text">Дата создания: {{ object.created_at|date:"d.m.Y H:i:s" }}</h5>
    </div> 
</div>


{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset enable>
        <legend>Добавить товар</legend>
        <form method="post" class="my-class">
            {{ form|crispy }}
        </form>
        <button type="submit" class="btn btn-primary">Создать</button>
    </fieldset>
</form>

{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    
    <fieldset enable>
        <legend>Изменить товар</legend>
        <form method="post" class="my-class">
            {% csrf_token %}
            {{ form|crispy }}
            {{ formset.management_form }}
            {% for formvers in formset %}
                <hr>
                {{formvers|crispy}}
            {% endfor %}
        </form>
        <button type="submit" class="btn btn-primary">Изменить</button>
    </fieldset>
</form>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_product_cart.html' %}
        {% endfor %}
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Пред.</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">След.</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_product_cart.html' %}
        {% endfor %}
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ products.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current-page">
            Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">следующая</a>
            <a href="?page={{ object_list.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}